### ISSUE TITLE
How to get fire base device token

### ISSUE THREAD

**Issue by uouo690** [imaginalis/spring-boot-fcm-push-notifications#2]
Hello ,

First of all , hanks for this useful project . 

But I have question , how to get device token from inside the spring boot back end, lets say I need to send a private message to user ,when I use web socket I use the other user name or login field, and spring boot will handle the rest of it.
   
As example :
`messagingTemplate.convertAndSendToUser("userName", "/queue/xxx", activityDTO);`
using this method spring boot handle the delivery of web socket message internally with no need to add any code.

Is there any kind of integration between spring boot and fire base in that way , or I have to implement some kind of code handling ,which mean when device authenticate I should send the fire base device token in http header and save it in a database , then when I need to send message to a device ,then get the related fire base token from database and use it to send push message.

Thanks for your valuable contribution

**Comment by imaginalis** [comment]
Hello @uouo690, thanks for your comment. 

If you're able to, you can save the device token to the Firebase database from your mobile app level. 
You can check it out, I've done it [here](https://blog.mestwin.net/get-your-simple-push-notifications-app-with-ionic-4-and-firebase-cloud-messaging/) using Ionic Framework and Cloud Firestore.

At this point, you'll be able to get the token stored in the Firebase database from the Spring Boot application level.

Then, if you already have the device token, you'll be able to send notifications to the users directly.

Hope it helped
