### ISSUE TITLE
"FirebaseApp with name [DEFAULT] doesn't exist

### ISSUE THREAD

**Issue by akshayurs123** [imaginalis/spring-boot-fcm-push-notifications#3]
Hi Imaginalis , 

Went through you blog very nicely explained. I also downloaded this project I am getting this error in response:
"FirebaseApp with name [DEFAULT] doesn't exist:
Have also added .json file in google/ folder.

![Capture](https://user-images.githubusercontent.com/6871064/78815165-7bd52e00-79ed-11ea-8c02-263da89a0782.PNG)

I ran this on my local server. Can you point out what I am missing ? 
I also noticed this issue mentioned on your blog: https://blog.mestwin.net/ but couldn't find an answer in the thread.

Thanks
Akshay

**Comment by imaginalis** [comment]
Hey @akshayurs123 👋  

Please check, if you have created and configured your Firebase app correctly.
